Tweak LBFGS to allow PyTree inputs
blackjax-devs/blackjax pull request #232
Opened 2022-06-27 21:36 UTC by ahwillia

This addresses https://github.com/blackjax-devs/blackjax/issues/227.

It passes tests locally on my machine, but should probably add an explicit test for a more complex pytree input. Let me know your thoughts.

One thing I'm not sure about is whether you want to count on `LbfgsState` being a stable feature of `jaxopt`. It might make sense to only unravel the fields in `LBFGSHistory`.

2022-06-28 05:11 UTC, junpenglao requested changes

2022-06-28 05:11 UTC, junpenglao commented on blackjax/optimizers/lbfgs.py
> +        ).astype(history_raveled.update_mask.dtype),
```suggestion
        update_mask=jax.tree_map(
            lambda x: x.astype(history_raveled.update_mask.dtype), 
            unravel_fn_mapped(history_raveled.update_mask.astype(x0_raveled.dtype))
        ),
```

2022-06-28 05:14 UTC, junpenglao commented
You also need to change the import in Pathfinder (and other places where `minimize_lbfgs` is initially called) to 
```python
from blackjax.vi.pathfinder import _minimize_lbfgs
```

2022-06-28 21:57 UTC, ahwillia commented
Thanks for the review, I cleaned those items up.

2022-06-29 05:23 UTC, junpenglao requested changes
`test_optimizers.py` also need update.

2022-06-29 06:20 UTC, junpenglao commented
Actually, we can leave the test as is (still works as unravel is a non-op there)

2022-06-29 06:20 UTC, merged