Independent RMH implementation
blackjax-devs/blackjax pull request #246
Opened 2022-07-04 20:30 UTC by ciguaran

This is related to https://github.com/blackjax-devs/blackjax/issues/245

- Adds Independent RMH, adds a simple test in test_sampling.py
- Refactors RMH so that it takes a proposal distribution, vs the current behavior that takes a proposal for the movement wrt the current state. Maintains backwards compatibility.

2022-07-04 20:31 UTC, ciguaran commented on tests/test_sampling.py
> +irmh_test_case = {
I extracted this in order to have it close to the comment explaining the rationale for the proposal distribution. LMK if other format is preferred.

2022-07-05 11:13 UTC, rlouf commented on blackjax/mcmc/irmh.py
> +"""Public API for Rosenbluth-Metropolis-Hastings kernels."""
```suggestion
"""Public API for the Independent Rosenbluth-Metropolis-Hastings kernels."""
```

2022-07-05 11:13 UTC, rlouf commented on blackjax/mcmc/irmh.py
> +
We try to keep this convention throughout the library

2022-07-05 11:14 UTC, rlouf commented on blackjax/mcmc/irmh.py
> +
Is there a paper from the literature that you could reference here?

2022-07-05 11:16 UTC, rlouf commented on blackjax/mcmc/rmh.py
> +        We temporally assume that the proposal distribution is symmetric.
```suggestion
        We temporarily assume that the proposal distribution is symmetric.
```

2022-07-05 11:17 UTC, rlouf commented on blackjax/mcmc/rmh.py
> -    proposal_generator: Callable,
Good catch, naming was indeed ambiguous

2022-07-05 11:20 UTC, rlouf commented
Thank you for the contribution! Can you briefly explain what the difference between RHM and independent RMH is exactly so I can keep reviewing?

2022-07-05 12:58 UTC, junpenglao commented
> Thank you for the contribution! Can you briefly explain what the difference between RHM and independent RMH is exactly so I can keep reviewing?

From my understanding, RMH transition is `f(x) -> random.normal(loc=x, scale=scale)` and Independent transition is `g(_) -> random.normal(loc=x, scale=scale)`, in the later case `x` is fixed (e.g., estimate from higher temperature in SMC). The same MH accept-reject still applies in both cases.

2022-07-05 14:19 UTC, ciguaran commented
Check Algorithm 2 here : https://arxiv.org/pdf/2008.02455.pdf

2022-07-06 18:49 UTC, ciguaran commented on blackjax/kernels.py
> +
The thing is that at some point we need users to be able to run something like
`blackjax.adaptive_tempered_smc(
    logprior,
    loglikelihood,
    blackjax.irmh,
    irmh_parameters,
    resampling.systematic,
    target_ess=0.8,
    mcmc_iter=10)`

So they need to be able to reference IRMH in order to run it (even as SMC kernel).  Unless there's a better place for SMC kernels that are only meant to be used in that context.

2022-07-07 18:38 UTC, rlouf commented on blackjax/mcmc/irmh.py
> +    Returns
nitpick: linebreak

2022-07-07 18:38 UTC, rlouf commented on blackjax/mcmc/irmh.py
> +def kernel(proposal_distribution: Callable):
Can you add a return type here?

2022-07-07 18:47 UTC, rlouf commented on blackjax/kernels.py
> +
I see. We didn't propagate recent design changes in the library to SMC but that's totally fine, discard my earlier comment we can leave this here for now.

2022-07-07 18:56 UTC, rlouf commented
In `rmh.py`: I think `rmh_with_proposal_generator` should be called `rmh`, and move `proposal_generator` that's inside the current `rmh` function to `kenel` . We'll the revisit the general design in #162, and this PR.

2022-07-11 15:22 UTC, rlouf requested changes

2022-07-11 15:22 UTC, rlouf commented on blackjax/mcmc/rmh.py
> +        raise ValueError
We need tests that cover these two branches.

2022-07-11 18:25 UTC, merged

2022-07-11 18:25 UTC, rlouf commented
Awesome, thank you!