Gather all types in a single place
blackjax-devs/blackjax pull request #79
Opened 2021-07-29 17:45 UTC by AdrienCorenflos

2021-07-29 18:59 UTC, rlouf commented on blackjax/common.py
> +from typing import Dict, List, Tuple, Union
Could we name it `types.py` ?

2021-07-29 19:01 UTC, rlouf commented
Thank you for opening this PR. Now we are working on meta-algorithms (SMC, parallel tempering, coupling) it is time that we start thinking about types across the library.

2021-07-30 09:00 UTC, junpenglao commented on blackjax/common.py
> +Array = Union[jnp.ndarray, jnp.DeviceArray, float]
```suggestion
Array = Union[np.ndarray, jnp.DeviceArray]
```

2021-08-01 13:22 UTC, rlouf requested changes
I think we can merge once the `PRNGKey` type is added.

2021-08-01 13:26 UTC, AdrienCorenflos commented
You sure you want to do this? It feels like it may be confusing for end
users...

On Sun, 1 Aug 2021, 16:22 Rémi Louf, ***@***.***> wrote:

> ***@***.**** requested changes on this pull request.
>
> I think we can merge once the PRNGKey type is added.
> ------------------------------
>
> In blackjax/common.py
> <https://github.com/blackjax-devs/blackjax/pull/79#discussion_r680499918>:
>
> > @@ -0,0 +1,6 @@
> +from typing import Dict, List, Tuple, Union
> +
> +import jax.numpy as jnp
> +
> +Array = Union[np.ndarray, jnp.DeviceArray]
> +PyTree = Union[Dict, List, Tuple, Array]
>
> Could you add the type PRNGKey = Array ?
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/blackjax-devs/blackjax/pull/79#pullrequestreview-719654392>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AEYGFZ7C4W7IT2AMUBGHVULT2VDDHANCNFSM5BG57ZWQ>
> .
>

2021-08-01 13:46 UTC, rlouf commented
How would it be confusing ? Because the name of the function that returns a key is `jax.random.PRNGKey`?

It may be for a split second for someone who edits the code, but I think would be very readable for others.

2021-08-01 15:56 UTC, rlouf commented
Interested in knowing why you thought this would be confusing.

2021-08-01 18:26 UTC, rlouf commented
Looks like you need to import the names in many files still, and fix the linting. After that we're good to merge.

2021-08-02 06:07 UTC, merged

2021-08-02 06:07 UTC, junpenglao commented
Nice! Thanks @AdrienCorenflos!